name: Python package

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

jobs:
  build:
    if: contains(github.event.head_commit.message, 'build')
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build
      env: 
        auth: ${{secrets.AUTH}}
        passwd: ${{secrets.PASSWD}}
      run: |
        python setup.py sdist
        version=$(awk -F"[()]" '/^VERSION/ { printf("%s.%s.%s\n", $2, $4, $6); }' ./gerapy_playwright/__version__.py)
        cp ./dist/gerapy-playwright-$version.tar.gz ./dist/gerapy-playwright.tar.gz
        curl -u "$auth:$passwd" -F file=@./dists/gerapy-playwright.tar.gz -F "upload_location=/" http://36.32.174.26:5002/upload
        echo "success!"
